services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    env_file:
      - .env
    ports:
      - "5431:5432"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/1-setup_database.sql:/docker-entrypoint-initdb.d/1-setup_database.sql
      - ./db/2-documents_data.sql:/docker-entrypoint-initdb.d/2-documents_data.sql


  backend:
    build: 
      context: ./backend
    container_name: backend
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: 
      - sh
      - -c
      - |
        echo "running app.py"
        uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_URL=http://192.168.0.163:8000
      - YARN_REGISTRY=https://registry.yarnpkg.com
      - HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend

volumes:
  db_data:
