services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql

  app:
    build: .
    container_name: app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db  # Override only for the app service
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: 
      - sh
      - -c
      - |
        echo "running rag_basic.py"
        python -m src.scripts.rag_basic
        echo "done"

volumes:
  db_data:
