services:
  db:
    image: pgvector/pgvector:pg17
    container_name: ultirules_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./setup_database.sql:/app/setup_database.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: ["postgres", "-c", "log_statement=all"]

  app:
    build: .
    container_name: ultirules_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: /bin/bash -c "tail -f /dev/null"
    tty: true
    stdin_open: true

volumes:
  db_data:
