services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: ["postgres", "-c", "log_statement=ddl"] # ddl

  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # restart: unless-stopped
    # command: 
    #   - sh
    #   - -c
    #   - |
    #     echo "creating vectorstore"
    #     python prepare_vectorstore/create_vectorstore.py
    #     echo "querying vectorstore"
    #     python query_vectorstore.py
    #     echo "done"
    command: 
      - sh
      - -c
      - |
        echo "querying vectorstore"
        python query_vectorstore.py

volumes:
  db_data:
