services:
  db:
    image: pgvector/pgvector:pg17
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql

  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: 
      - sh
      - -c
      - |
        echo "running app.py"
        uvicorn src.ultimate_rules_rag.app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: 
      context: ./ultimate-rules-chat
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ultimate-rules-chat:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - YARN_REGISTRY=https://registry.yarnpkg.com
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend

volumes:
  db_data:
